---
- block:
    - name: "Register Systems with Satellite or CDN"
      include_tasks: register.yml
      tags: [register]

    - name: "Enable and disable Repositories"
      include_tasks: repos.yml
      tags: [repos]

    - name: "Clean up AWS instance if using aws."
      include_tasks: aws_cleanup.yml
      tags: [aws]

    - name: "Install packages required by satellite"
      include_tasks: packages.yml
      tags: [pkgs]
  become: true 
