---

- name: "Download Satellite or Capsule RPM"
  get_url:
    url: "https://{{ rh_satserver }}/{{ rh_satserver_rpm_path }}"
    validate_certs: no
    dest: "{{ rh_workingdir }}/{{ rh_rpmname }}"
    mode: '0740'
  when:
    - rh_usesat == "yes"
    - rh_satserver is defined

- name: "Install Satellite or Capsule RPM"
  yum:
    name: "{{ rh_workingdir }}/{{ rh_rpmname }}" 
    state: present
  when:
    - rh_usesat == "yes"
    - rh_satserver is defined

- name: "Register with Red Hat using activation key."
  redhat_subscription:
    state: present
    activationkey: "{{ rh_ak }}"
    org_id: "{{ rh_orgid }}"
    force_register: "{{ rh_forceregister }}" 
  when: 
    - rh_forceregister != "no"
    - rh_ak is defined

- name: "Register with Red Hat using credentials."
  redhat_subscription:
    state: present
    username: "{{ rh_username }}"
    password: "{{ rh_password }}"
    org_id: "{{ rh_orgid }}"
    force_register: "{{ rh_forceregister }}"
  when: 
    - rh_forceregister != "no"
    - rh_ak is not defined
